import React, { FormEvent, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Search, Plus } from "lucide-react";
import { usePortalData } from "../../hooks/usePortalData";
import { SupportRequestStatus, VisaCaseStatus } from "../../types/portal";

type Role = "visa" | "student" | "support";
type Page = "dashboard" | "cases" | "documents" | "tasks" | "notifications" | "profile" | "applications" | "requests" | "activities";
const Badge: React.FC<{ value: string }> = ({ value }) => <span className="px-2 py-0.5 sq-badge bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">{value}</span>;
const Table: React.FC<{ title: string; heads: string[]; rows: React.ReactNode[][] }> = ({ title, heads, rows }) => <section className="bg-[var(--bg-card)] border border-[var(--border-default)] sq-card overflow-hidden"><h2 className="p-4 font-bold text-sm text-[var(--text-primary)]">{title}</h2>{rows.length === 0 ? <p className="p-10 text-center text-[var(--text-muted)]">No records available.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[var(--bg-elevated)] text-[var(--text-muted)] uppercase"><tr>{heads.map((head) => <th key={head} className="p-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-[var(--border-default)]">{rows.slice(0, 10).map((row, index) => <tr key={index}>{row.map((cell, column) => <td key={column} className="p-3 text-[var(--text-secondary)]">{cell}</td>)}</tr>)}</tbody></table></div>}</section>;

export const RolePortal: React.FC<{ role: Role; page: Page }> = ({ role, page }) => {
  const data = usePortalData(); const [search, setSearch] = useState(""); const [modal, setModal] = useState(false); const [notice, setNotice] = useState("");
  const cases = useMemo(() => data.visaCases.filter((item) => `${item.studentName} ${item.country} ${item.status}`.toLowerCase().includes(search.toLowerCase())), [data.visaCases, search]);
  const requests = useMemo(() => data.requests.filter((item) => `${item.studentName} ${item.subject} ${item.status}`.toLowerCase().includes(search.toLowerCase())), [data.requests, search]);
  const title = role === "visa" ? "Visa Officer" : role === "student" ? "Student Portal" : "Support Operations";
  const cards = role === "visa" ? [["Active cases", data.visaCases.length], ["Needs documents", data.visaCases.filter((x) => x.status === "Documents Pending").length], ["Appointments", data.visaCases.filter((x) => x.status === "Appointment Scheduled").length], ["Granted", data.visaCases.filter((x) => x.status === "Granted").length]] : role === "student" ? [["Applications", data.ownApplications.length], ["Documents", data.ownDocuments.length], ["Pending actions", data.ownTasks.filter((x) => x.status !== "Completed").length], ["Visa updates", data.visaCases.filter((x) => x.studentId === data.ownStudent?.id).length]] : [["Open requests", data.requests.filter((x) => x.status === "Open").length], ["Assigned tasks", data.tasks.filter((x) => x.assignedTo === data.ownStudent?.email).length], ["Escalated", data.requests.filter((x) => x.status === "Escalated").length], ["Student issues", data.requests.filter((x) => x.category === "Student Issue").length]];
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { if (role === "student" && page === "documents" && data.ownStudent) { const file = form.get("file"); if (!(file instanceof File) || file.size === 0) throw new Error("Select a document file before uploading."); await data.uploadDocument({ studentId: data.ownStudent.id, studentName: data.ownStudent.fullName, documentType: String(form.get("documentType")), deadline: String(form.get("deadline") || "") }, file); } if ((role === "support" || (role === "student" && page === "requests")) && (role !== "student" || data.ownStudent)) await data.createRequest({ studentId: role === "student" ? data.ownStudent!.id : String(form.get("studentId") || ""), studentName: role === "student" ? data.ownStudent!.fullName : String(form.get("studentName")), category: form.get("category") as "Student Issue", priority: form.get("priority") as "Low", subject: String(form.get("subject")), description: String(form.get("description")), assignedTo: "" }); setNotice("Saved successfully."); setModal(false); } catch (error: any) { setNotice(error.message || "Unable to save. Check permissions and try again."); } };
  if (data.loading) return <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{Array.from({ length: 4 }, (_, i) => <div key={i} className="h-28 animate-pulse bg-[var(--bg-card)] border border-[var(--border-default)] sq-card" />)}</div>;
  return <div className="space-y-6 text-xs"><header className="flex flex-col sm:flex-row justify-between gap-4"><div><h1 className="text-2xl font-bold font-heading text-[var(--text-primary)]">{title} - {page === "dashboard" ? "Dashboard" : page}</h1><p className="text-[var(--text-secondary)] mt-1">Role-scoped records and actions only.</p></div><div className="flex gap-2">{(role === "student" && page === "applications") && <Link to="/student/new-application" className="px-4 py-2 bg-emerald-500 text-zinc-950 font-bold sq-btn flex items-center gap-1.5"><Plus className="w-3.5 h-3.5" />New Application</Link>}{(page === "requests" || (role === "student" && page === "documents")) && <button onClick={() => setModal(true)} className="px-4 py-2 bg-emerald-500 text-zinc-950 font-bold sq-btn">{page === "requests" ? "New Request" : "Upload Document"}</button>}</div></header>{data.error && <p className="p-3 text-rose-400 bg-rose-500/10 border border-rose-500/20 sq-card">{data.error}</p>}{notice && <p className="p-3 text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 sq-card">{notice}</p>}
    {page === "dashboard" && <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{cards.map(([label, value]) => <div key={label as string} className="p-4 bg-[var(--bg-card)] border border-[var(--border-default)] sq-card"><p className="uppercase font-bold text-[var(--text-muted)]">{label}</p><p className="mt-3 text-2xl font-bold text-[var(--text-primary)]">{value as number}</p></div>)}</div>{role === "student" && <Link to="/student/new-application" className="block p-4 bg-gradient-to-r from-emerald-500/10 to-teal-500/10 border border-emerald-500/20 sq-card hover:border-emerald-500/40 transition-colors group"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-emerald-500/20 border border-emerald-500/30 rounded-xl flex items-center justify-center"><Plus className="w-5 h-5 text-emerald-400" /></div><div><p className="font-bold text-sm text-[var(--text-primary)] group-hover:text-emerald-400 transition-colors">Submit a New Application</p><p className="text-[var(--text-muted)] mt-0.5">Apply directly to a university programme from your portal</p></div></div></Link>}<div className="grid lg:grid-cols-2 gap-6"><Table title="Upcoming deadlines" heads={["Case / Task", "Deadline", "Status"]} rows={[...data.visaCases.filter((x) => x.deadline).map((x) => [x.studentName, x.deadline || "-", <Badge value={x.status} />]), ...data.ownTasks.filter((x) => x.dueDate).map((x) => [x.title, x.dueDate, <Badge value={x.status} />])]} /><Table title="Recent activities" heads={["Item", "Update"]} rows={[...data.requests.slice(0, 5).map((x) => [x.subject, x.status]), ...data.visaCases.slice(0, 5).map((x) => [x.studentName, x.status])]} /></div></>}
    {(page === "cases" || page === "applications") && <><SearchBar value={search} setValue={setSearch} />{role === "visa" ? <Table title="Visa case management" heads={["Student", "University", "Country", "Status", "Priority", "Update"]} rows={cases.map((item) => [item.studentName, item.universityName || "-", item.country, <Badge value={item.status} />, item.priority, <select aria-label="Visa case status" value={item.status} onChange={(e) => data.updateVisa(item, e.target.value as VisaCaseStatus)} className="p-1 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input">{["Preparation", "Documents Pending", "Under Review", "Appointment Scheduled", "Submitted", "Granted", "Refused", "Escalated"].map((x) => <option key={x}>{x}</option>)}</select>])} /> : <Table title="My applications" heads={["Student", "University", "Programme", "Status", "Intake"]} rows={data.ownApplications.map((item) => [item.studentName, item.universityName, item.programmeName, <Badge value={item.stage} />, item.intake])} />}</>}
    {page === "documents" && <Table title={role === "visa" ? "Visa document review" : "My documents"} heads={["Student", "Document", "File", "Status", "Remarks", "Action"]} rows={(role === "student" ? data.ownDocuments : data.documents).map((item) => [item.studentName, item.documentType, item.fileName, <Badge value={item.status} />, item.remarks || "-", role === "visa" ? <select aria-label="Document status" value={item.status} onChange={(e) => data.updateDocument(item, e.target.value as typeof item.status)} className="p-1 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input">{["Missing", "Pending", "Verified", "Rejected"].map((x) => <option key={x}>{x}</option>)}</select> : <button onClick={() => setModal(true)} className="text-emerald-400 underline">Upload replacement</button>])} />}
    {page === "tasks" && <Table title="Tasks and actions" heads={["Task", "Due", "Priority", "Status", "Action"]} rows={(role === "student" ? data.ownTasks : data.tasks).map((task) => [task.title, task.dueDate, task.priority, <Badge value={task.status} />, <button onClick={() => data.updateTask(task)} className="text-emerald-400 underline">{task.status === "Completed" ? "Reopen" : "Complete"}</button>])} />}
    {page === "profile" && <Profile student={data.ownStudent} onSave={data.saveProfile} setNotice={setNotice} />}
    {page === "requests" && <><SearchBar value={search} setValue={setSearch} /><Table title={role === "student" ? "My support requests" : "Support requests / assigned cases"} heads={["Student", "Subject", "Category", "Priority", "Status", "Update"]} rows={requests.map((item) => [item.studentName, item.subject, item.category, item.priority, <Badge value={item.status} />, role === "student" ? "Awaiting support update" : <select aria-label="Support request status" value={item.status} onChange={(e) => data.updateRequest(item, e.target.value as SupportRequestStatus)} className="p-1 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input">{["Open", "In Progress", "Waiting on Student", "Resolved", "Escalated"].map((x) => <option key={x}>{x}</option>)}</select>])} /></>}
    {page === "activities" && <Table title="Operational activity history" heads={["Request", "Status", "Updated"]} rows={data.requests.map((item) => [item.subject, item.status, new Date(item.updatedAt).toLocaleDateString()])} />}
    {page === "notifications" && <Table title="Portal notifications" heads={["Event", "Detail", "Priority"]} rows={[...data.documents.filter((x) => x.status === "Rejected" || x.status === "Missing").map((x) => ["Document action", `${x.documentType} for ${x.studentName}`, "High"]), ...data.visaCases.filter((x) => x.status === "Granted" || x.status === "Refused").map((x) => ["Visa decision", `${x.studentName}: ${x.status}`, "High"]), ...data.requests.filter((x) => x.status === "Escalated").map((x) => ["Escalation", x.subject, "Urgent"])]} />}
    {modal && <Form role={role} page={page} students={data.students} onSubmit={submit} close={() => setModal(false)} />}</div>;
};
const SearchBar: React.FC<{ value: string; setValue: (value: string) => void }> = ({ value, setValue }) => <div className="relative max-w-md"><Search className="absolute w-4 h-4 left-3 top-2.5 text-[var(--text-muted)]" /><input value={value} onChange={(e) => setValue(e.target.value)} placeholder="Search records..." className="w-full p-2 pl-9 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input" /></div>;
const Profile: React.FC<{ student: ReturnType<typeof usePortalData>["ownStudent"]; onSave: ReturnType<typeof usePortalData>["saveProfile"]; setNotice: (x: string) => void }> = ({ student, onSave, setNotice }) => !student ? <p className="p-8 text-center text-[var(--text-muted)]">Your student profile is being prepared.</p> : <form onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave(student, { phone: String(f.get("phone")), countryOfResidence: String(f.get("country")), notes: String(f.get("emergency")) }); setNotice("Profile updated."); }} className="max-w-2xl p-6 space-y-4 bg-[var(--bg-card)] border border-[var(--border-default)] sq-card"><h2 className="font-bold text-sm">My profile</h2><Input name="name" label="Full legal name" value={student.fullName} disabled /><Input name="phone" label="Phone" value={student.phone} /><Input name="country" label="Country of residence" value={student.countryOfResidence} /><Input name="emergency" label="Emergency contact" value={student.notes || ""} /><button className="px-4 py-2 bg-emerald-500 text-zinc-950 font-bold sq-btn">Save permitted changes</button></form>;
const Form: React.FC<{ role: Role; page: Page; students: ReturnType<typeof usePortalData>["students"]; onSubmit: (e: FormEvent<HTMLFormElement>) => void; close: () => void }> = ({ role, page, students, onSubmit, close }) => <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[var(--backdrop)]"><form onSubmit={onSubmit} className="w-full max-w-md p-6 space-y-3 bg-[var(--bg-card)] border border-[var(--border-default)] sq-modal"><h2 className="font-bold">{role === "student" && page === "documents" ? "Upload document" : "New support request"}</h2>{role === "student" && page === "documents" ? <><Input name="documentType" label="Document type" /><label className="block text-[var(--text-secondary)]">Document file<input name="file" type="file" required accept="application/pdf,image/jpeg,image/png,image/webp,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="w-full p-2 mt-1 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input" /></label><Input name="deadline" label="Deadline" type="date" /></> : <><select name="studentId" className="w-full p-2 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input">{students.map((s) => <option key={s.id} value={s.id}>{s.fullName}</option>)}</select>{role !== "student" && <Input name="studentName" label="Student name" />}<Input name="subject" label="Subject" /><Input name="description" label="Description" /><select name="category" className="w-full p-2 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input"><option>Student Issue</option><option>Application Issue</option><option>Document Issue</option><option>Technical</option><option>Other</option></select><select name="priority" className="w-full p-2 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></>}<div className="flex justify-end gap-2"><button type="button" onClick={close} className="px-3 py-2 sq-btn bg-[var(--bg-hover)]">Cancel</button><button className="px-3 py-2 sq-btn bg-emerald-500 text-zinc-950 font-bold">Save</button></div></form></div>;
const Input: React.FC<{ name: string; label: string; value?: string; type?: string; disabled?: boolean }> = ({ name, label, value, type = "text", disabled }) => <label className="block text-[var(--text-secondary)]">{label}<input name={name} type={type} defaultValue={value} disabled={disabled} required={!disabled} className="w-full p-2 mt-1 bg-[var(--bg-input)] border border-[var(--border-default)] sq-input" /></label>;
