import React, { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AlertCircle, ArrowRight, GraduationCap, MapPin, Search } from "lucide-react";
import { useGlobalData } from "../../contexts/GlobalDataContext";
import { usePortalData } from "../../hooks/usePortalData";
import { Programme, University } from "../../types/university";
import { assessEligibility } from "../../utils/eligibility";

const fallbackImage = "/sample_transcript.jpg";
const money = (value: number, currency: string) => new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
const programmesFor = (university: University) => university.programmes || [];
const stageProgress: Record<string, number> = { Draft: 15, "Documents Pending": 30, "Initial Review": 40, "Ready for Submission": 55, Submitted: 65, "University Reviewing": 75, "Conditional Offer": 85, "Unconditional Offer": 90, "Deposit Pending": 92, "CAS / COE Pending": 95, "Visa Preparation": 97, Enrolled: 100 };

const Cover: React.FC<{ university: University; className?: string }> = ({ university, className = "" }) => <img src={university.coverImageUrl || university.logoUrl || fallbackImage} alt={university.coverImageAlt || `${university.name} campus`} loading="lazy" onError={(event) => { event.currentTarget.src = fallbackImage; }} className={`object-cover ${className}`} />;
const EligibilityBadge: React.FC<{ programme: Programme; student: ReturnType<typeof usePortalData>["ownStudent"] }> = ({ programme, student }) => { const result = assessEligibility(student, programme); const style = result.status === "eligible" ? "bg-emerald-50 text-emerald-700" : result.status === "not_eligible" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-800"; const label = result.status === "eligible" ? "Meets configured requirements" : result.status === "not_eligible" ? "Needs improvement" : "Needs review"; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${style}`}>{label}</span>; };

export const StudentDashboard: React.FC = () => {
  const { ownStudent, ownApplications, ownDocuments, ownTasks } = usePortalData();
  const { universities } = useGlobalData();
  const navigate = useNavigate();
  const name = ownStudent?.fullName?.split(" ")[0] || "there";
  const completeness = ownStudent?.profileCompleteness || 0;
  const action = ownApplications.find((app) => app.nextAction) ? { text: ownApplications.find((app) => app.nextAction)?.nextAction || "Continue your application", href: "/student/applications" } : completeness < 80 ? { text: "Complete your profile to improve application readiness", href: "/student/profile" } : ownDocuments.length === 0 ? { text: "Upload your essential documents", href: "/student/documents" } : { text: "Explore a programme that matches your profile", href: "/student/programs" };
  const active = ownApplications.filter((app) => !["Rejected", "Withdrawn", "Enrolled"].includes(app.stage));
  return <div className="mx-auto max-w-7xl space-y-7 pb-8">
    <header className="rounded-3xl bg-slate-900 px-6 py-8 text-white shadow-xl sm:px-8"><p className="text-sm font-medium text-emerald-300">STUDENT ADMISSIONS PORTAL</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Good morning, {name}.</h1><p className="mt-2 max-w-xl text-sm text-slate-300">Here is an overview of your university application journey and the next best step to take.</p></header>
    <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-900">Profile completion</p><p className="mt-1 text-sm text-slate-500">A complete profile lets us reuse your information across every application.</p></div><span className="text-3xl font-bold text-emerald-600">{completeness}%</span></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${completeness}%` }} /></div><Link to="/student/profile" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Complete profile <ArrowRight className="h-4 w-4" /></Link></div>
      <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><AlertCircle className="mt-0.5 h-5 w-5 text-amber-700" /><div><p className="font-semibold text-slate-900">Your next step</p><p className="mt-1 text-sm text-slate-600">{action.text}</p><button onClick={() => navigate(action.href)} className="mt-4 text-sm font-bold text-amber-800 underline">Complete now</button></div></div></div></section>
    <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-900">Your applications</h2><p className="text-sm text-slate-500">Track progress, deadlines, and required actions in one place.</p></div><Link to="/student/applications" className="text-sm font-semibold text-emerald-700">View all</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.slice(0, 3).map((application) => { const university = universities.find((item) => item.id === application.universityId); const progress = stageProgress[application.stage] || 25; return <article key={application.id} className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><Cover university={university || { id: "fallback", name: application.universityName, country: "", city: "", programmes: [], createdAt: 0, updatedAt: 0 }} className="h-32 w-full" /><div className="p-5"><p className="font-semibold text-slate-900">{application.universityName}</p><p className="mt-1 text-sm text-slate-500">{application.programmeName}</p><p className="mt-4 text-xs font-bold uppercase tracking-wide text-emerald-700">{application.stage}</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-sm text-slate-600">{application.nextAction || "Waiting for the next application update"}</p><Link to={`/student/applications/${application.id}`} className="mt-4 inline-block text-sm font-bold text-slate-900">View application →</Link></div></article>; })}{active.length === 0 && <Empty title="You have not started an application yet" action="Explore universities" href="/student/universities" />}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold text-slate-900">Upcoming deadlines</h2>{ownTasks.filter((task) => task.dueDate).slice(0, 4).map((task) => <div key={task.id} className="mt-4 flex items-center justify-between border-b border-slate-100 pb-3 text-sm"><span className="font-medium text-slate-700">{task.title}</span><span className="text-slate-500">{task.dueDate}</span></div>)}{ownTasks.length === 0 && <p className="mt-3 text-sm text-slate-500">No deadlines need your attention today.</p>}</div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold text-slate-900">Recommended for you</h2>{universities.slice(0, 2).map((university) => <Link key={university.id} to={`/student/universities/${university.id}`} className="mt-4 flex items-center gap-3"><Cover university={university} className="h-12 w-12 rounded-xl" /><div><p className="font-medium text-slate-800">{university.name}</p><p className="text-xs text-slate-500">{university.city}, {university.country}</p></div></Link>)}</div></section>
  </div>;
};

const Empty: React.FC<{ title: string; action: string; href: string }> = ({ title, action, href }) => <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center md:col-span-2 xl:col-span-3"><GraduationCap className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 font-semibold text-slate-700">{title}</p><Link to={href} className="mt-3 inline-block text-sm font-bold text-emerald-700">{action} →</Link></div>;

export const StudentUniversities: React.FC = () => { const { universities } = useGlobalData(); const [search, setSearch] = useState(""); const filtered = universities.filter((university) => `${university.name} ${university.country} ${university.city}`.toLowerCase().includes(search.toLowerCase())); return <div className="mx-auto max-w-7xl space-y-6 pb-8"><header><p className="text-sm font-semibold text-emerald-700">DISCOVER</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Explore universities</h1><p className="mt-2 text-slate-500">Find a university, understand its programmes, and check your fit before applying.</p></header><label className="relative block max-w-xl"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by university, city, or country" className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-12 pr-4 shadow-sm outline-none focus:border-emerald-500" /></label><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((university) => <article key={university.id} className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><Cover university={university} className="h-44 w-full" /><div className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">{university.country}</p><h2 className="mt-1 text-lg font-bold text-slate-900">{university.name}</h2><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><MapPin className="h-4 w-4" />{university.city}</p><p className="mt-3 line-clamp-2 text-sm text-slate-600">{university.description || "Explore programmes, requirements, intakes, and application deadlines."}</p><div className="mt-4 flex items-center justify-between text-sm"><span className="font-medium text-slate-600">{programmesFor(university).length} programmes</span><Link to={`/student/universities/${university.id}`} className="font-bold text-emerald-700">View university →</Link></div></div></article>)}</div>{!filtered.length && <Empty title="No universities match your search" action="Clear search" href="/student/universities" />}</div>; };

export const StudentUniversityDetail: React.FC = () => { const { universityId } = useParams(); const { universities } = useGlobalData(); const university = universities.find((item) => item.id === universityId); if (!university) return <div className="p-8 text-slate-600">University not found or is no longer available.</div>; return <div className="mx-auto max-w-6xl space-y-6 pb-8"><div className="overflow-hidden rounded-3xl bg-slate-900 text-white"><Cover university={university} className="h-64 w-full opacity-60" /><div className="-mt-24 relative p-7"><p className="text-sm text-emerald-300">{university.city}, {university.country}</p><h1 className="mt-1 text-3xl font-bold">{university.name}</h1><p className="mt-3 max-w-2xl text-slate-200">{university.description || "Programme and admission details are maintained by the education team."}</p><a href={university.website?.startsWith("http") ? university.website : `https://${university.website}`} target="_blank" rel="noreferrer" className="mt-5 inline-block text-sm font-bold text-white underline">Official website</a></div></div><section><h2 className="text-xl font-bold text-slate-900">Popular programmes</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{programmesFor(university).map((programme) => <ProgrammeCard key={programme.id} university={university} programme={programme} />)}</div></section></div>; };

const ProgrammeCard: React.FC<{ university: University; programme: Programme }> = ({ university, programme }) => { const { ownStudent } = usePortalData(); return <article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-bold uppercase text-emerald-700">{programme.level}</p><h3 className="mt-1 font-bold text-slate-900">{programme.title}</h3><p className="mt-2 text-sm text-slate-500">{programme.durationMonths} months · {money(programme.tuitionFeeAnnual, programme.currency)}</p><div className="mt-4 flex flex-wrap gap-2"><EligibilityBadge programme={programme} student={ownStudent} /><Link to={`/student/programs/${university.id}-${programme.id}`} className="ml-auto text-sm font-bold text-slate-900">View programme →</Link></div></article>; };

export const StudentProgrammes: React.FC = () => { const { universities } = useGlobalData(); const [search, setSearch] = useState(""); const items = useMemo(() => universities.flatMap((university) => programmesFor(university).map((programme) => ({ university, programme }))).filter((item) => `${item.university.name} ${item.programme.title} ${item.university.country} ${item.programme.level}`.toLowerCase().includes(search.toLowerCase())), [universities, search]); return <div className="mx-auto max-w-7xl space-y-6 pb-8"><header><p className="text-sm font-semibold text-emerald-700">DISCOVER</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Find a programme</h1><p className="mt-2 text-slate-500">Requirements are an indication only. Final admission decisions are made by the university.</p></header><label className="relative block max-w-xl"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search programme, university, country, or degree" className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-12 pr-4 shadow-sm outline-none focus:border-emerald-500" /></label><div className="grid gap-4 lg:grid-cols-2">{items.map(({ university, programme }) => <ProgrammeCard key={`${university.id}-${programme.id}`} university={university} programme={programme} />)}</div></div>; };

export const StudentProgramDetail: React.FC = () => { const { programId } = useParams(); const { universities } = useGlobalData(); const { ownStudent } = usePortalData(); const found = universities.flatMap((university) => programmesFor(university).map((programme) => ({ university, programme }))).find((item) => `${item.university.id}-${item.programme.id}` === programId); if (!found) return <div className="p-8 text-slate-600">Programme not found.</div>; const result = assessEligibility(ownStudent, found.programme); const color = result.status === "eligible" ? "emerald" : result.status === "not_eligible" ? "rose" : "amber"; return <div className="mx-auto max-w-5xl space-y-6 pb-8"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-bold text-emerald-700">{found.university.name} · {found.university.city}</p><h1 className="mt-2 text-3xl font-bold text-slate-900">{found.programme.title}</h1><div className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-4"><span>{found.programme.level}</span><span>{found.programme.durationMonths} months</span><span>{money(found.programme.tuitionFeeAnnual, found.programme.currency)}</span><span>{found.programme.intakes.join(", ")}</span></div></div><section className={`rounded-2xl border bg-${color}-50 p-6`}><h2 className="text-lg font-bold text-slate-900">Based on your profile: {result.status.replace("_", " ")}</h2><p className="mt-2 text-sm text-slate-600">{result.disclaimer}</p><div className="mt-4 space-y-3">{result.checks.map((check) => <div key={check.label} className="rounded-xl bg-white p-3 text-sm shadow-sm"><span className="font-semibold text-slate-800">{check.status === "pass" ? "✓" : check.status === "fail" ? "✕" : "!"} {check.label}</span><p className="mt-1 text-slate-600">{check.detail}</p></div>)}</div><Link to={`/student/new-application?universityId=${found.university.id}&programmeId=${found.programme.id}`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Start application <ArrowRight className="h-4 w-4" /></Link></section></div>; };
