/**
 * EduCRM — Country & Immigration Intelligence Types
 * Canonical type definitions for the Global Country Discovery Hub (Step 2).
 */

/* ------------------------------------------------------------------ */
/*  Destination Country                                                */
/* ------------------------------------------------------------------ */

export type TuitionAffordabilityTier = '$' | '$$' | '$$$';

export type WorldRegion =
  | 'All'
  | 'Popular Hubs'
  | 'Europe'
  | 'North America'
  | 'Asia-Pacific'
  | 'Middle East'
  | 'Latin America'
  | 'Africa';

export interface DestinationCountry {
  id: string;
  name: string;
  code: string;
  flag: string;
  currency: string;
  region: 'Europe' | 'North America' | 'Asia-Pacific' | 'Middle East' | 'Latin America' | 'Africa';
  tuitionAffordabilityTier: TuitionAffordabilityTier;
  pswvLengthYears: number;
  popularIntakes: string[];
  partnerCount: number;
  averageTuition: string;
  isPopular?: boolean;
}

/* ------------------------------------------------------------------ */
/*  Immigration Advisory                                               */
/* ------------------------------------------------------------------ */

export interface ImmigrationAdvisory {
  country: string;
  visaType: string;
  financialProof: {
    amount: string;
    description: string;
  };
  pswvRights: {
    duration: string;
    description: string;
  };
  languageAcceptance: string[];
  intakeMilestones: string[];
  complianceWarnings: string[];
  partnerCount: number;
  biometricRequired: boolean;
  studyGapLimitYears: number;
  healthInsuranceRequired: boolean;
  tuitionAffordabilityTier: TuitionAffordabilityTier;
  estimatedMonthlyLiving?: string;
  minIeltsOverall?: number;
}

/* ------------------------------------------------------------------ */
/*  Global Worldwide Destination Catalog (60+ Countries)               */
/* ------------------------------------------------------------------ */

export const DEFAULT_DESTINATIONS: DestinationCountry[] = [
  // --- Popular Hubs & North America ---
  {
    id: 'uk',
    name: 'United Kingdom',
    code: 'UK',
    flag: '🇬🇧',
    currency: 'GBP',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 2,
    popularIntakes: ['September', 'January', 'May'],
    partnerCount: 142,
    averageTuition: '£14,000 – £28,000',
    isPopular: true,
  },
  {
    id: 'ca',
    name: 'Canada',
    code: 'CA',
    flag: '🇨🇦',
    currency: 'CAD',
    region: 'North America',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 3,
    popularIntakes: ['September', 'January', 'May'],
    partnerCount: 89,
    averageTuition: 'CAD 18,000 – 35,000',
    isPopular: true,
  },
  {
    id: 'us',
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    currency: 'USD',
    region: 'North America',
    tuitionAffordabilityTier: '$$$',
    pswvLengthYears: 3,
    popularIntakes: ['Fall (Aug)', 'Spring (Jan)', 'Summer (May)'],
    partnerCount: 205,
    averageTuition: '$20,000 – $45,000',
    isPopular: true,
  },
  {
    id: 'au',
    name: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    currency: 'AUD',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$$$',
    pswvLengthYears: 2,
    popularIntakes: ['February', 'July', 'November'],
    partnerCount: 41,
    averageTuition: 'AUD 22,000 – 42,000',
    isPopular: true,
  },
  {
    id: 'de',
    name: 'Germany',
    code: 'DE',
    flag: '🇩🇪',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1.5,
    popularIntakes: ['Winter (Oct)', 'Summer (Apr)'],
    partnerCount: 38,
    averageTuition: '€0 – €14,000',
    isPopular: true,
  },
  {
    id: 'ie',
    name: 'Ireland',
    code: 'IE',
    flag: '🇮🇪',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 2,
    popularIntakes: ['September', 'January'],
    partnerCount: 26,
    averageTuition: '€11,000 – €24,000',
    isPopular: true,
  },
  {
    id: 'nz',
    name: 'New Zealand',
    code: 'NZ',
    flag: '🇳🇿',
    currency: 'NZD',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 3,
    popularIntakes: ['February', 'July'],
    partnerCount: 18,
    averageTuition: 'NZD 24,000 – 38,000',
    isPopular: true,
  },
  {
    id: 'ae',
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    currency: 'AED',
    region: 'Middle East',
    tuitionAffordabilityTier: '$$$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'January'],
    partnerCount: 22,
    averageTuition: 'AED 38,000 – 75,000',
    isPopular: true,
  },
  {
    id: 'sg',
    name: 'Singapore',
    code: 'SG',
    flag: '🇸🇬',
    currency: 'SGD',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$$$',
    pswvLengthYears: 1,
    popularIntakes: ['August', 'January'],
    partnerCount: 14,
    averageTuition: 'SGD 22,000 – 48,000',
    isPopular: true,
  },

  // --- Western & Northern Europe ---
  {
    id: 'fr',
    name: 'France',
    code: 'FR',
    flag: '🇫🇷',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 2,
    popularIntakes: ['September', 'January'],
    partnerCount: 32,
    averageTuition: '€3,000 – €16,000',
    isPopular: true,
  },
  {
    id: 'nl',
    name: 'Netherlands',
    code: 'NL',
    flag: '🇳🇱',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'February'],
    partnerCount: 24,
    averageTuition: '€8,000 – €20,000',
    isPopular: true,
  },
  {
    id: 'ch',
    name: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
    currency: 'CHF',
    region: 'Europe',
    tuitionAffordabilityTier: '$$$',
    pswvLengthYears: 0.5,
    popularIntakes: ['September', 'February'],
    partnerCount: 12,
    averageTuition: 'CHF 1,500 – 35,000',
  },
  {
    id: 'se',
    name: 'Sweden',
    code: 'SE',
    flag: '🇸🇪',
    currency: 'SEK',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 1,
    popularIntakes: ['August', 'January'],
    partnerCount: 16,
    averageTuition: 'SEK 90,000 – 160,000',
  },
  {
    id: 'it',
    name: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'February'],
    partnerCount: 28,
    averageTuition: '€1,000 – €14,000',
  },
  {
    id: 'es',
    name: 'Spain',
    code: 'ES',
    flag: '🇪🇸',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'January'],
    partnerCount: 25,
    averageTuition: '€2,500 – €16,000',
  },
  {
    id: 'be',
    name: 'Belgium',
    code: 'BE',
    flag: '🇧🇪',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'February'],
    partnerCount: 15,
    averageTuition: '€2,000 – €10,000',
  },
  {
    id: 'at',
    name: 'Austria',
    code: 'AT',
    flag: '🇦🇹',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['October', 'March'],
    partnerCount: 12,
    averageTuition: '€1,500 – €8,000',
  },
  {
    id: 'dk',
    name: 'Denmark',
    code: 'DK',
    flag: '🇩🇰',
    currency: 'DKK',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 2,
    popularIntakes: ['September', 'February'],
    partnerCount: 11,
    averageTuition: 'DKK 50,000 – 110,000',
  },
  {
    id: 'no',
    name: 'Norway',
    code: 'NO',
    flag: '🇳🇴',
    currency: 'NOK',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 1,
    popularIntakes: ['August'],
    partnerCount: 8,
    averageTuition: 'NOK 80,000 – 150,000',
  },
  {
    id: 'fi',
    name: 'Finland',
    code: 'FI',
    flag: '🇫🇮',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 2,
    popularIntakes: ['August', 'January'],
    partnerCount: 14,
    averageTuition: '€6,000 – €18,000',
  },
  {
    id: 'pl',
    name: 'Poland',
    code: 'PL',
    flag: '🇵🇱',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['October', 'February'],
    partnerCount: 22,
    averageTuition: '€2,000 – €6,000',
  },
  {
    id: 'pt',
    name: 'Portugal',
    code: 'PT',
    flag: '🇵🇹',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'February'],
    partnerCount: 16,
    averageTuition: '€1,500 – €7,000',
  },
  {
    id: 'cz',
    name: 'Czech Republic',
    code: 'CZ',
    flag: '🇨🇿',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0.75,
    popularIntakes: ['September', 'February'],
    partnerCount: 18,
    averageTuition: '€3,000 – €9,000',
  },
  {
    id: 'hu',
    name: 'Hungary',
    code: 'HU',
    flag: '🇭🇺',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0.75,
    popularIntakes: ['September', 'February'],
    partnerCount: 15,
    averageTuition: '€3,000 – €8,000',
  },
  {
    id: 'cy',
    name: 'Cyprus',
    code: 'CY',
    flag: '🇨🇾',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['October', 'February'],
    partnerCount: 19,
    averageTuition: '€4,000 – €9,000',
  },
  {
    id: 'mt',
    name: 'Malta',
    code: 'MT',
    flag: '🇲🇹',
    currency: 'EUR',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0.5,
    popularIntakes: ['October', 'February'],
    partnerCount: 9,
    averageTuition: '€5,000 – €11,000',
  },

  // --- Asia-Pacific ---
  {
    id: 'my',
    name: 'Malaysia',
    code: 'MY',
    flag: '🇲🇾',
    currency: 'MYR',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['September', 'March'],
    partnerCount: 28,
    averageTuition: 'MYR 20,000 – 45,000',
    isPopular: true,
  },
  {
    id: 'jp',
    name: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    currency: 'JPY',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 1,
    popularIntakes: ['April', 'September'],
    partnerCount: 21,
    averageTuition: '¥700,000 – 1,400,000',
    isPopular: true,
  },
  {
    id: 'kr',
    name: 'South Korea',
    code: 'KR',
    flag: '🇰🇷',
    currency: 'KRW',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['March', 'September'],
    partnerCount: 20,
    averageTuition: '₩4,000,000 – 9,000,000',
    isPopular: true,
  },
  {
    id: 'cn',
    name: 'China',
    code: 'CN',
    flag: '🇨🇳',
    currency: 'CNY',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'March'],
    partnerCount: 35,
    averageTuition: '¥20,000 – 50,000',
  },
  {
    id: 'hk',
    name: 'Hong Kong',
    code: 'HK',
    flag: '🇭🇰',
    currency: 'HKD',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 2,
    popularIntakes: ['September', 'January'],
    partnerCount: 8,
    averageTuition: 'HKD 140,000 – 210,000',
  },
  {
    id: 'th',
    name: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    currency: 'THB',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['August', 'January'],
    partnerCount: 14,
    averageTuition: 'THB 120,000 – 250,000',
  },
  {
    id: 'id',
    name: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    currency: 'USD',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['September', 'February'],
    partnerCount: 11,
    averageTuition: '$2,500 – $6,000',
  },
  {
    id: 'in',
    name: 'India',
    code: 'IN',
    flag: '🇮🇳',
    currency: 'INR',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['July', 'January'],
    partnerCount: 45,
    averageTuition: '₹150,000 – 500,000',
  },
  {
    id: 'pk',
    name: 'Pakistan',
    code: 'PK',
    flag: '🇵🇰',
    currency: 'PKR',
    region: 'Asia-Pacific',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['Fall', 'Spring'],
    partnerCount: 26,
    averageTuition: 'PKR 300,000 – 800,000',
  },

  // --- Middle East & Eurasia ---
  {
    id: 'tr',
    name: 'Turkey',
    code: 'TR',
    flag: '🇹🇷',
    currency: 'USD',
    region: 'Middle East',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'February'],
    partnerCount: 29,
    averageTuition: '$2,000 – $9,000',
    isPopular: true,
  },
  {
    id: 'sa',
    name: 'Saudi Arabia',
    code: 'SA',
    flag: '🇸🇦',
    currency: 'SAR',
    region: 'Middle East',
    tuitionAffordabilityTier: '$$',
    pswvLengthYears: 1,
    popularIntakes: ['September', 'January'],
    partnerCount: 10,
    averageTuition: 'SAR 30,000 – 60,000',
  },
  {
    id: 'qa',
    name: 'Qatar',
    code: 'QA',
    flag: '🇶🇦',
    currency: 'QAR',
    region: 'Middle East',
    tuitionAffordabilityTier: '$$$',
    pswvLengthYears: 0,
    popularIntakes: ['September', 'January'],
    partnerCount: 7,
    averageTuition: 'QAR 50,000 – 90,000',
  },
  {
    id: 'ge',
    name: 'Georgia',
    code: 'GE',
    flag: '🇬🇪',
    currency: 'USD',
    region: 'Europe',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['October', 'March'],
    partnerCount: 16,
    averageTuition: '$3,500 – $7,000',
  },

  // --- Latin America & Africa ---
  {
    id: 'za',
    name: 'South Africa',
    code: 'ZA',
    flag: '🇿🇦',
    currency: 'ZAR',
    region: 'Africa',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['February', 'July'],
    partnerCount: 12,
    averageTuition: 'ZAR 45,000 – 85,000',
  },
  {
    id: 'eg',
    name: 'Egypt',
    code: 'EG',
    flag: '🇪🇬',
    currency: 'USD',
    region: 'Africa',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['September', 'February'],
    partnerCount: 11,
    averageTuition: '$3,000 – $8,000',
  },
  {
    id: 'ke',
    name: 'Kenya',
    code: 'KE',
    flag: '🇰🇪',
    currency: 'USD',
    region: 'Africa',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['September', 'January'],
    partnerCount: 8,
    averageTuition: '$2,000 – $5,000',
  },
  {
    id: 'ng',
    name: 'Nigeria',
    code: 'NG',
    flag: '🇳🇬',
    currency: 'NGN',
    region: 'Africa',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['September', 'January'],
    partnerCount: 14,
    averageTuition: 'NGN 1,000,000 – 3,000,000',
  },
  {
    id: 'br',
    name: 'Brazil',
    code: 'BR',
    flag: '🇧🇷',
    currency: 'BRL',
    region: 'Latin America',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 1,
    popularIntakes: ['February', 'August'],
    partnerCount: 10,
    averageTuition: 'R$ 15,000 – 35,000',
  },
  {
    id: 'mx',
    name: 'Mexico',
    code: 'MX',
    flag: '🇲🇽',
    currency: 'USD',
    region: 'Latin America',
    tuitionAffordabilityTier: '$',
    pswvLengthYears: 0,
    popularIntakes: ['August', 'January'],
    partnerCount: 9,
    averageTuition: '$3,000 – $7,500',
  },
];
